version: '3'
services:
  backend:
    build: backend/.
    ports:
    - "8080:8080"
    container_name: backend-container
  nginx:
    build: nginx/.
    container_name: nginx
    ports:
    - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"